stages:
  preprocess:
    cmd: python -m src.data.preprocess
    deps:
    - data/raw/house_prices.csv
    - src/data/preprocess.py
    outs:
    - data/processed/house_prices.csv
  train:
    cmd: python -m src.models.train
    params:
    - data.test_size
    - models.random_forest_regressor.max_depth
    - models.random_forest_regressor.n_estimators
    - models.decision_tree_regressor.max_depth
    - training.random_seed
    outs:
    - models/model.pkl
