models:
  
    linear_regression : {}

    random_forest_regressor:
      n_estimators: 100
      max_depth: 8

    decision_tree_regressor:
      max_depth: 15

  
data:
  raw_path: "/home/fidisroxy/development/mlops/house-pred-mlops/data/raw/house_prices.csv"
  processed_path: "/home/fidisroxy/development/mlops/house-pred-mlops/data/processed/house_prices.csv"
  test_size: 0.2


training:
  random_seed: 42
  experiment_name: The Trinity